### PR TITLE
fix(agent): scope callable tools to owner-published agents and polish build UX

### LINKED ISSUE #27: bug: Published Agent Visible to All Users in Tools → Agent Category
### Description

After an agent is published, it becomes visible to all users under the Tools → Agent category.

Currently, once an agent is published, there is no restriction on its visibility scope. This may lead to unintended exposure of agents that were meant to be private

### Steps to Reproduce

1. Create a new agent
2. Publish the agent
3. Navigate to Tools → Agent
4. Observe that the published agent is visible to all users.

### Expected Behavior

The visibility of a published agent should be controllable. For example:

- Private (only creator)
- Team / Organization scoped
- Public (visible to all users)

### PR DESCRIPTION
**Pull request by bluefish-08**
**Summary**
Fixes #27 by aligning callable behavior with publish status.
- `draft`: not callable
- `published`: callable for the owner’s own agents only

**Changes**
- Backend: scope agent tool discovery to owner + published status.
- Frontend: keep publish flow in-place on `/build/{id}` and improve feedback UX.
- Tests: add status-based coverage for publish/unpublish callable behavior.

### CODE REVIEW

File: frontend/src/components/build/agent-builder.tsx [hunk 1]
```diff
@@ -1294,24 +1323,54 @@ export function AgentBuilder({ agentId }: AgentBuilderProps) {
...
+        <div className="fixed top-5 left-1/2 -translate-x-1/2 z-50">
+          <div
+            role="status"
+            aria-live="polite"
+            className={`inline-flex items-center px-4 py-2 rounded-md border border-emerald-300 bg-emerald-50 text-emerald-700 text-sm shadow-sm transition-all duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] ${successVisible ? "opacity-100 translate-y-0 scale-100" : "opacity-0 -translate-y-1.5 scale-95"}`}
+          >
+            {successMessage}
+          </div>
+        </div>
+      )}
```
Comment (yiboyasss) [inline frontend/src/components/build/agent-builder.tsx]: We have added a new dependency, **sonner**, for the error message component. You can display `errorMessage` and `successMessage` by using:

```ts
import { toast } from "sonner"
```

Comment (qinxuye) [reply frontend/src/components/build/agent-builder.tsx]: There is conflict I will resolve and force push.
